apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firehose-remote-write

images:
  - name: IMAGE:TAG
    newName: docker.io/petergrace/firehose_remote_write
    newTag: v0.1.3
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- ns.yaml
